### ISSUE TITLE
Generated text files not showing up 

### ISSUE THREAD

**Issue by itsdefprince** [DrkTheDon/drkgen#2]
I have successfully installed everything but the codes don’t generate. It tells me where to find the generated gift card but the path doesn’t even exist. Where should I look for these txt files

**Comment by itsdefprince** [comment]
I knew to cd the file but I guess it was one of those bugs that fix themselves. I have another question, do the generated txt files actually work or are they just supposed to fit the format or the selected gift card

**Comment by DrkTheDon** [comment]
They are generated, the chance is not big at all. one may work out of 100k I think depends.
