### ISSUE TITLE
Whats the point?

### ISSUE THREAD

**Issue by xman213** [DrkTheDon/drkgen#3]
The gens dont check the code. This is kind of useless in my opinon. idk if it checked them it would be cool

**Comment by CloovyYT** [comment]
> The gens dont check the code. This is kind of useless in my opinon. idk if it checked them it would be cool

Working on a fix to this rn, if i can do it I will post it.

**Comment by CloovyYT** [comment]
> The gens dont check the code. This is kind of useless in my opinon. idk if it checked them it would be cool

https://discord.gg/6UeygmJB Not for sure if you have to pay, but I know that it will have checkers.

**Comment by DrkTheDon** [comment]
I was going to make DrkGEN 2.0 (selling it) but I always got disocrd termed, cant sell it so add me on discord to get the src code drk#4697.
